version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/food-buddy
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #   develop:
  #     watch:
  #       - path: pom.xml
  #         action: rebuild
  #       - path: .
  #         target: /src
  #         action: rebuild

volumes:
  postgres_data:
